#!/usr/bin/with-contenv bash
CONFD_DIR=/etc/nginx/conf.d
ENABLED_HTTP_FN=${CONFD_DIR}/default.conf
DISABLED_HTTP_FN=${ENABLED_HTTP_FN}.disabled
ENABLED_HTTPS_FN=${CONFD_DIR}/default-ssl.conf
DISABLED_HTTPS_FN=${ENABLED_HTTPS_FN}.disabled

function run_ssl {
  mv $DISABLED_HTTPS_FN $ENABLED_HTTPS_FN || true
  mv $ENABLED_HTTP_FN $DISABLED_HTTPS_FN || true
  exec /usr/sbin/nginx
}

if [[ -f /etc/ssl/acme/fullchain.pem ]]; then
  run_ssl
else
  mv $DISABLED_HTTP_FN $ENABLED_HTTP_FN || true
  mv $ENABLED_HTTPS_FN $DISABLED_HTTPS_FN || true
  exec /usr/sbin/nginx &
  nginx_pid=$!
  acme-client -vNn $SSL_DOMAIN
  kill $nginx_pid
  run_ssl
fi

exec /usr/sbin/nginx
